# Defines the path to store VM images
kvm_images_path: /var/lib/libvirt/images

# Define default disk image cache mode
## none, writethrough, writeback, directsync, and unsafe
kvm_images_cache_mode: none

kvm_images_format_type: qcow2

