sudo tee -a /etc/yum.repos.d/google-cloud-sdk.repo << EOM
[google-cloud-sdk]
name=Google Cloud SDK
baseurl=https://packages.cloud.google.com/yum/repos/cloud-sdk-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
       https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOM



yum install google-cloud-sdk -y


sudo yum install kubectl -y


sudo yum install google-cloud-sdk-anthos-auth -y


gcloud components update


sudo yum makecache && sudo yum update kubectl google-cloud-sdk-anthos-auth google-cloud-sdk-minikube google-cloud-sdk google-cloud-sdk-app-engine-go google-cloud-sdk-pubsub-emulator google-cloud-sdk-kind google-cloud-sdk-firestore-emulator google-cloud-sdk-kpt google-cloud-sdk-cloud-build-local google-cloud-sdk-datastore-emulator google-cloud-sdk-spanner-emulator google-cloud-sdk-app-engine-python google-cloud-sdk-skaffold google-cloud-sdk-bigtable-emulator google-cloud-sdk-cbt google-cloud-sdk-app-engine-grpc google-cloud-sdk-app-engine-python-extras google-cloud-sdk-datalab google-cloud-sdk-app-engine-java -y


