# Just for reference variables 
# These variables aren't used for automation


Seesaw load balancers:
========================

Admin Cluster:
    VIP1: 192.168.2.21
    VIP2: 192.168.2.22

    Seesaw VM IP: 192.168.2.23
    Master IP for the Seesaw LB: 192.168.2.24

User Cluster:
    VIP1: 192.168.2.25
    VIP2: 192.168.2.26

    Seesaw VM IP: 192.168.2.27
    Master IP for the Seesaw LB: 192.168.2.28
    

# ADMIN Cluster - admin-seesaw-hostconfig.yaml
#-----------------------
hostconfig:
  dns: "192.168.2.1"
  tod: "192.138.210.214"
  otherdns:
  - "8.8.8.8"
  - "8.8.4.4"
  othertod:
  - "ntp.ubuntu.com"
  searchdomainsfordns:
  - "my.local.com"
blocks:
  - netmask: "255.255.255.0"
    gateway: "192.168.2.1"
    ips:
    - ip: "192.168.2.23"
      hostname: "ac-seesaw-vm"
#-----------------------


# USER Cluster - Seesaw VM Host config file
#-----------------------
hostconfig:
  dns: "192.168.2.1"
  tod: "192.138.210.214"
  otherdns:
  - "8.8.8.8"
  - "8.8.4.4"
  othertod:
  - "ntp.ubuntu.com"
  searchdomainsfordns:
  - "my.local.com"
blocks:
  - netmask: "255.255.255.0"
    gateway: "192.168.2.1"
    ips:
    - ip: "192.168.2.27"
      hostname: "uc-seesaw-vm"
#-----------------------



#====================================================
# admin-ws-config.yaml
#====================================================

gcp:
  whitelistedServiceAccountKeyPath: "/root/pradeesi-c25276a32cbb.json"
vCenter:
  credentials:
    address: "192.168.2.5"
    username: "administrator@vsphere.local"
    password: "P@ssw0rd"
  datacenter: "Datacenter"
  datastore: "datastore2"
  cluster: "Cluster"
  network: "VM Network"
  resourcePool: "Cluster/Resources"
  caCertPath: "/root/certs/lin/e65bea3e.0"
proxyUrl: ""
adminWorkstation:
  name: gke-admin-ws-200815-192127
  cpus: 4
  memoryMB: 8192
  diskGB: 50
  dataDiskName: gke-on-prem-admin-workstation-data-disk/gke-admin-ws-200815-192127-data-disk.vmdk
  dataDiskMB: 512
  network:
    ipAllocationMode: "static"
    hostConfig:
      ip: "192.168.2.11"
      gateway: "192.168.2.1"
      netmask: "255.255.255.0"
      dns:
        - "192.168.2.1"
  proxyUrl: ""
  ntpServer: ntp.ubuntu.com

#====================================================




#====================================================
# admin-hostconfig.yaml
#====================================================

hostconfig:
  dns: 192.168.2.1
  tod: 216.239.35.0
  otherdns:
  - 8.8.8.8
  - 8.8.4.4
  othertod:
  - ntp.ubuntu.com
  searchdomainsfordns:
  - "my.local.com"
blocks:
  - netmask: 255.255.252.0
    gateway: 192.168.2.1
    ips:
    - ip: 192.168.2.31
      hostname: admin-host1
    - ip: 192.168.2.32
      hostname: admin-host2
    - ip: 192.168.2.33
      hostname: admin-host3
    - ip: 192.168.2.34
      hostname: admin-host4
    - ip: 192.168.2.35
      hostname: admin-host5

#====================================================



#====================================================
# user-hostconfig.yaml
#====================================================
hostconfig:
  dns: 192.168.2.1
  tod: 216.239.35.0
  otherdns:
  - 8.8.8.8
  - 8.8.4.4
  othertod:
  - ntp.ubuntu.com
  searchdomainsfordns:
  - "my.local.com"
blocks:
  - netmask: 255.255.252.0
    gateway: 172.16.23.254
    ips:
    - ip: 192.168.2.41
      hostname: user-host1
    - ip: 172.16.20.42
      hostname: user-host2
    - ip: 172.16.20.43
      hostname: user-host3
#====================================================