---
# ------------------------------------------
# file: global_config_vars/vcenter_config.yml
# ver: 1.0
# ansible ver: 2.7.8
# python ver: 2.7.15
# author: Pradeep Singh
# description: Vmware vCenter Config Variables
# ------------------------------------------


# vmware vCenter server config
vcenter:
  version: 6.5
  name: Embedded-vCenter-Server-Appliance
  ip_address: 192.168.2.5
  dns_servers: 192.168.2.1
  subnet_prefix: 24
  gateway: 192.168.2.1
  system_name: 192.168.2.5
  os_password: P@ssw0rd
  sso_password: P@ssw0rd
  sso_domain_name: vsphere.local
  sso_site_name: mysite
  esxi_host:
    kvm_vm_name: esxi1
    hostname: 192.168.2.6
    username: root
    password: P@ssw0rd
    deployment_network: VM Network
    datastore: datastore1
  vcenter_config:
    datacenter_name: Datacenter
    esxi_cluster:
      cluster_name: Cluster
      enable_drs: false
      enable_ha: false
      enable_vsan: false
      esxi_hosts:     
        - kvm_vm_name: esxi1
        - kvm_vm_name: esxi2
    distributed_virtual_switch:
      dvs_name: DSwitch
      version: 6.0.0
      port_group_name: Anthos-PG
      port_group_vlan_id: 0
      esxi_hosts:
        - kvm_vm_name: esxi1
          vmnic: vmnic1
        - kvm_vm_name: esxi2
          vmnic: vmnic1









