---
# ------------------------------------------
# file: roles/vcenter_master/tasks/check_esxi_vm_readiness.yml
# ver: 1.0
# ansible ver: 2.7.8
# python ver: 2.7.15
# author: Pradeep Singh
# description: Check if the ESXi vm is available and powered on
# ------------------------------------------


# Variables - 
# esxi_host_kvm_vm_name
# esxi_host_ip


# Check if ESXi vm exists
- name: List All VMs
  command: "virsh list --all --name"
  become: true
  register: vms_on_kvm

- name: Check is ESXi server exists
  block:

    # Check if ESXi vm is powered-on
    - name: List Running VMs
      command: "virsh list --all --name --state-running"
      become: true
      register: running_vms

      # Power on ESXi if its powered off
    - name: Power-on ESXi host
      block: 

        - name: "Power on ESXi VM - {{esxi_host_kvm_vm_name}}"
          command: "virsh start {{esxi_host_kvm_vm_name}}"
          become: true
        
        - name: Wait for ESXi host to become ready
          wait_for:
            host: "{{esxi_host_ip}}"
            port: "80"
            delay: 20
            state: started

      when: not (running_vms.stdout | regex_search( esxi_host_kvm_vm_name ))

  when: (vms_on_kvm.stdout | regex_search( esxi_host_kvm_vm_name ))


- name: Fail if ESXi VM isn't available on KVM Host
  fail:
    msg: "Unable to find ESXi Host {{esxi_host_kvm_vm_name}}. Please check the vcenter configuration in the 'vcenter_config.yml' file."
  when: not (vms_on_kvm.stdout | regex_search( esxi_host_kvm_vm_name ))


- name: Make sure ESXi is ready
  wait_for:
    host: "{{esxi_host_ip}}"
    port: "80"
    delay: 1
    timeout: 300     # Host provisioning may take time.
    state: started
  register: esxi_readiness_status
  ignore_errors: True

# Initiate Recursion, if the previous activity failed.
- name: Recursion - Check ESXi host readiness on KVM once again...
  include_tasks: check_esxi_vm_readiness.yml
  when: esxi_readiness_status.failed

- name: sleep for 10 seconds and continue with play
  wait_for:
    timeout: 10
 

