---
# ------------------------------------------
# file: ansible/roles/vcenter_master/tasks/configure_vcenter.yml
# ansible ver: 2.7.8
# python ver: 2.7.15
# author: Pradeep Singh
# description: This task will configure vCenter server after installation
# ------------------------------------------


# Create vCenter Datacenter
- name: Create vCenter Datacenter - "{{vcenter.vcenter_config.datacenter_name}}"
  vmware_datacenter:
    hostname: "{{vcenter.ip_address}}"
    username: "administrator@{{vcenter.sso_domain_name}}"
    password: "{{vcenter.sso_password}}"
    validate_certs: no
    datacenter_name: "{{vcenter.vcenter_config.datacenter_name}}"
    state: present

# Create vCenter Cluster
- name: Create vCenter Cluster - "{{vcenter.vcenter_config.esxi_cluster.cluster_name}}"
  vmware_cluster:
    hostname: "{{vcenter.ip_address}}"
    username: "administrator@{{vcenter.sso_domain_name}}"
    password: "{{vcenter.sso_password}}"
    validate_certs: no
    datacenter_name: "{{vcenter.vcenter_config.datacenter_name}}"
    cluster_name: "{{vcenter.vcenter_config.esxi_cluster.cluster_name}}"

# Enable DRS
- name: Enable DRS on vCenter Cluster - "{{vcenter.vcenter_config.esxi_cluster.cluster_name}}"
  vmware_cluster_drs:
    hostname: "{{vcenter.ip_address}}"
    username: "administrator@{{vcenter.sso_domain_name}}"
    password: "{{vcenter.sso_password}}"
    validate_certs: no
    datacenter_name:  "{{vcenter.vcenter_config.datacenter_name}}"
    cluster_name: "{{vcenter.vcenter_config.esxi_cluster.cluster_name}}"
    enable_drs: yes
  when: 
    - vcenter.vcenter_config.esxi_cluster.enable_drs

# Enable vSAN
- name: Enable vSAN and claim storage automatically on vCenter Cluster - "{{vcenter.vcenter_config.esxi_cluster.cluster_name}}"
  vmware_cluster_vsan:
    hostname: "{{vcenter.ip_address}}"
    username: "administrator@{{vcenter.sso_domain_name}}"
    password: "{{vcenter.sso_password}}"
    validate_certs: no
    datacenter_name: "{{vcenter.vcenter_config.datacenter_name}}"
    cluster_name: "{{vcenter.vcenter_config.esxi_cluster.cluster_name}}"
    enable_vsan: True
    vsan_auto_claim_storage: True
  when: 
    - vcenter.vcenter_config.esxi_cluster.enable_vsan

# Enable HA
- name: Enable HA on vCenter Cluster - "{{vcenter.vcenter_config.esxi_cluster.cluster_name}}"
  vmware_cluster_ha:
    hostname: "{{vcenter.ip_address}}"
    username: "administrator@{{vcenter.sso_domain_name}}"
    password: "{{vcenter.sso_password}}"
    validate_certs: no
    datacenter_name: "{{vcenter.vcenter_config.datacenter_name}}"
    cluster_name: "{{vcenter.vcenter_config.esxi_cluster.cluster_name}}"
    enable_ha: yes
  when: 
    - vcenter.vcenter_config.esxi_cluster.enable_ha


# Register ESXi Hosts to vCenter Server
- name: Register ESXi Hosts onto vCenter Server
  include_tasks: register_esxi_on_vcenter.yml
  with_items: "{{ vcenter.vcenter_config.esxi_cluster.esxi_hosts }}"
  loop_control:
    loop_var: esxi_host_item
  when:
    - vcenter.vcenter_config.esxi_cluster.esxi_hosts is defined

# Create Distributed virtual switch
- name: Create dvSwitch
  vmware_dvswitch:
    hostname: "{{vcenter.ip_address}}"
    username: "administrator@{{vcenter.sso_domain_name}}"
    password: "{{vcenter.sso_password}}"
    validate_certs: no
    datacenter_name: "{{vcenter.vcenter_config.datacenter_name}}"
    switch:  "{{vcenter.vcenter_config.distributed_virtual_switch.dvs_name}}"
    version: "{{vcenter.vcenter_config.distributed_virtual_switch.version}}"
    mtu: 9000
    uplink_quantity: 1
    discovery_protocol: lldp
    discovery_operation: both
    state: present
  when:
    - vcenter.vcenter_config.distributed_virtual_switch is defined
  

# Register ESXi Hosts to Distributed Virtual Switch 
- name: Register ESXi Hosts onto Distributed Virtual Switch 
  include_tasks: register_esxi_on_distributed_vswitch.yml
  with_items: "{{ vcenter.vcenter_config.distributed_virtual_switch.esxi_hosts }}"
  loop_control:
    loop_var: esxi_host_item
  when:
    - vcenter.vcenter_config.distributed_virtual_switch is defined

# Create Port Group on Distributed vSwitch
- name: "Create vlan - {{vcenter.vcenter_config.distributed_virtual_switch.port_group_vlan_id}}, portgroup - {{vcenter.vcenter_config.distributed_virtual_switch.port_group_name}}, on Distributed vSwitch - {{vcenter.vcenter_config.distributed_virtual_switch.dvs_name}}"
  vmware_dvs_portgroup:
    hostname: "{{vcenter.ip_address}}"
    username: "administrator@{{vcenter.sso_domain_name}}"
    password: "{{vcenter.sso_password}}"
    validate_certs: no
    portgroup_name: "{{vcenter.vcenter_config.distributed_virtual_switch.port_group_name}}"
    switch_name: "{{vcenter.vcenter_config.distributed_virtual_switch.dvs_name}}"
    vlan_id: "{{vcenter.vcenter_config.distributed_virtual_switch.port_group_vlan_id}}"
    num_ports: 120
    portgroup_type: earlyBinding
    state: present

